name: Solc Version Tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge tests for each supported solc version
        run: >
            forge test --use 0.8.4 &&
            forge test --use 0.8.5 &&
            forge test --use 0.8.6 &&
            forge test --use 0.8.7 &&
            forge test --use 0.8.8 &&
            forge test --use 0.8.9 &&
            forge test --use 0.8.10 &&
            forge test --use 0.8.11 &&
            forge test --use 0.8.12 &&
            forge test --use 0.8.13 &&
            forge test --use 0.8.14 &&
            forge test --use 0.8.15 &&
            forge test --use 0.8.16 &&
            forge test --use 0.8.17 &&
            forge test --use 0.8.18
